name: CICD Pipeline - Build & Deploy to render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  server-check:
    name: Server Check
    runs-on: ubuntu-latest
    steps:
      - name: Check system info
        run: |
          echo "Node Version:"
          node -v
          echo "Git Version:"
          git --version
          echo "Current Directory:"
          whoami && pwd && ls -a
          echo "GitHub Workspace:"
          echo $GITHUB_WORKSPACE

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: [server-check]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn build

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
